---
- name: condition learning
  hosts: web
  become: yes

  tasks: 
    - name: when condition
      yum: 
        name: bind-utils
        state: present
      when: ansible_distribution == "RedHat"
      register: output
    - debug: 
        msg: "My distribution is : {{ansible_distribution}} {{output}} {{inventory_hostname}}"